# Generated by Django 4.1.7 on 2023-03-28 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="phone number must be in the format : +213********* or 05/06/07********",
                        regex="^(\\+213|0)(5|6|7)[0-9]{8}$",
                    )
                ],
            ),
        ),
    ]
