# Generated by Django 4.1.7 on 2023-03-28 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid phone number ,phone number should be on the format : 5/6/7 (********)",
                        regex="^(5|6|7)[0-9]{8}$",
                    )
                ],
            ),
        ),
    ]
