# Generated by Django 4.1.7 on 2023-03-28 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid phone number",
                        regex="^(00213|\\+213|0)(5|6|7)[0-9]{8}$",
                    )
                ],
            ),
        ),
    ]
